from __future__ import annotations

from html import escape
from typing import Any

from app.services.document_model import normalize_document_model
from app.services.document_model import render_preview_html as render_document_preview_html


def build_content_model(
    format_name: str,
    *,
    title: str,
    source_text: str,
    content_model: dict[str, Any] | None = None,
    template: str | None = None,
) -> dict[str, Any]:
    normalized = format_name.lower().strip(".")
    lines = _clean_lines(source_text)
    if normalized == "xlsx":
        return {"kind": "spreadsheet", "title": title, "rows": _table_rows(lines), "source_text": source_text}
    if normalized == "pptx":
        return {"kind": "slides", "title": title, "slides": _slides(title, lines), "source_text": source_text}
    if normalized in {"pdf", "docx"}:
        return normalize_document_model(
            content_model,
            title=title,
            source_text=source_text,
            template=template,
        )
    return {"kind": "html", "title": title, "source_text": source_text}


def render_preview_html(format_name: str, model: dict[str, Any], html_content: str | None = None) -> str:
    normalized = format_name.lower().strip(".")
    if normalized in {"html", "web_app"} and html_content:
        return html_content
    if normalized == "xlsx":
        return _spreadsheet_preview(model)
    if normalized == "pptx":
        return _slides_preview(model)
    if normalized in {"pdf", "docx"}:
        return render_document_preview_html(model, "PDF" if normalized == "pdf" else "Word")
    if html_content:
        return html_content
    return _document_preview(model, "Document")


def _clean_lines(source_text: str) -> list[str]:
    return [line.strip(" \t-•") for line in source_text.splitlines() if line.strip(" \t-•")]


def _document_blocks(lines: list[str]) -> list[dict[str, str]]:
    if not lines:
        return [{"type": "paragraph", "text": "暂无正文内容。"}]
    blocks = []
    for line in lines:
        block_type = "heading" if len(line) <= 28 and not line.endswith(("。", ".", "；", ";")) else "paragraph"
        blocks.append({"type": block_type, "text": line})
    return blocks


def _table_rows(lines: list[str]) -> list[list[str]]:
    source = lines or ["事项,说明,状态", "内容生成,由 AgentHub 工具生成,完成"]
    rows: list[list[str]] = []
    for index, line in enumerate(source, start=1):
        if "|" in line:
            cells = [cell.strip() for cell in line.strip("|").split("|") if cell.strip()]
        elif "," in line:
            cells = [cell.strip() for cell in line.split(",") if cell.strip()]
        else:
            cells = [str(index), line, "完成"]
        rows.append(cells[:8])
    if len(rows) == 1:
        rows.insert(0, ["序号", "内容", "状态"])
    return rows[:80]


def _slides(title: str, lines: list[str]) -> list[dict[str, Any]]:
    body = lines or ["目标与背景", "方案设计", "执行计划", "验收标准"]
    slides = [{"title": title, "bullets": body[:3] or ["Generated by AgentHub"]}]
    for start in range(3, len(body), 4):
        slides.append({"title": body[start], "bullets": body[start + 1 : start + 4] or [body[start]]})
    return slides[:12]


def _document_preview(model: dict[str, Any], label: str) -> str:
    blocks = "".join(_document_block_html(block) for block in model.get("blocks", []))
    return _html_shell(
        "agenthub-word-preview",
        f"""
        <main class="page a4-page">
          <div class="label">{escape(label)} Document</div>
          <h1>{escape(str(model.get("title") or "AgentHub 文档"))}</h1>
          {blocks}
        </main>
        """,
    )


def _document_block_html(block: dict[str, str]) -> str:
    text = escape(str(block.get("text") or ""))
    if block.get("type") == "heading":
        return f"<h2>{text}</h2>"
    return f"<p>{text}</p>"


def _spreadsheet_preview(model: dict[str, Any]) -> str:
    rows = model.get("rows") or []
    table = "".join(
        f"<tr>{''.join(f'<td>{escape(str(cell))}</td>' for cell in row)}</tr>"
        for row in rows
    )
    return _html_shell(
        "agenthub-sheet-preview",
        f"""
        <main class="sheet-page">
          <div class="label">Excel Spreadsheet</div>
          <h1>{escape(str(model.get("title") or "AgentHub 表格"))}</h1>
          <table>{table}</table>
        </main>
        """,
    )


def _slides_preview(model: dict[str, Any]) -> str:
    cards = "".join(_slide_html(slide, index) for index, slide in enumerate(model.get("slides", []), start=1))
    return _html_shell(
        "agenthub-slides-preview",
        f"""
        <main class="slides-page">
          <div class="label">PowerPoint Deck</div>
          <section class="slides-grid">{cards}</section>
        </main>
        """,
    )


def _slide_html(slide: dict[str, Any], index: int) -> str:
    bullets = "".join(f"<li>{escape(str(item))}</li>" for item in slide.get("bullets", []))
    return f"<article class=\"slide\"><span>{index:02d}</span><h2>{escape(str(slide.get('title') or 'Slide'))}</h2><ul>{bullets}</ul></article>"


def _html_shell(class_name: str, body: str) -> str:
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><style>
body{{margin:0;background:#eef2f7;font-family:Inter,system-ui,sans-serif;color:#111827}}
.{class_name}{{min-height:100vh;padding:32px;box-sizing:border-box}}
.page,.sheet-page,.slides-page{{max-width:920px;margin:auto;background:white;border:1px solid #dce4ef;border-radius:8px;box-shadow:0 18px 60px rgba(15,23,42,.12)}}
.a4-page{{width:min(794px,100%);min-height:1123px;padding:64px;box-sizing:border-box}}
.label{{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#1677ff;font-weight:800;margin-bottom:18px}}
h1{{font-size:34px;line-height:1.15;margin:0 0 24px}}h2{{font-size:20px;margin:22px 0 8px}}p{{line-height:1.85;color:#374151}}
.sheet-page{{padding:28px}}table{{width:100%;border-collapse:collapse}}td{{border:1px solid #d6deea;padding:12px;vertical-align:top}}tr:first-child td{{background:#eef6ff;font-weight:700}}
.slides-page{{padding:28px;background:#f8fafc}}.slides-grid{{display:grid;gap:18px}}.slide{{min-height:240px;border:1px solid #dae3f0;border-radius:8px;background:white;padding:28px;box-shadow:0 10px 30px rgba(15,23,42,.08)}}.slide span{{color:#1677ff;font-weight:800}}
li{{margin:8px 0;line-height:1.6}}
</style></head><body><div class="{class_name}">{body}</div></body></html>"""
